# Change these first
owner: ashish-khokhar # Your GitHub organization or username, where this repository lives
repo: web-watch # The name of this repository

sites:
  - name: document.feasycom.com
    url: https://document.feasycom.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /web-watch
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Web Watch
  introTitle: "Web Watcher"
  introMessage: This is just a simple web watcher

assignees:
  - ashish-khokhar

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
